version: "2"
services:
    web:
        build: ./app
        links:
            - mongo
        volumes:
            - "./app:/src"
            - "/src/node_modules"
    mongo:
        image: mongo:latest
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - "./mongo/data/db:/data/db"
        ports:
            - 27017:27017
networks:
    default:
        external:
            name: main




